-- MySQL Script generated by MySQL Workbench
-- Tue May 30 16:43:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ilya_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ilya_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilya_db` DEFAULT CHARACTER SET latin1 ;
USE `ilya_db` ;

-- -----------------------------------------------------
-- Table `ilya_db`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilya_db`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`developers` (
  `dev_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT(11) NOT NULL,
  `companies_company_id` INT NOT NULL,
  INDEX `dev_id_idx` (`dev_id` ASC),
  PRIMARY KEY (`dev_id`, `companies_company_id`),
  INDEX `fk_developers_companies1_idx` (`companies_company_id` ASC),
  CONSTRAINT `fk_developers_companies1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `ilya_db`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilya_db`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`skills` (
  `skill_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name_skill` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilya_db`.`developers_has_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`developers_has_skills` (
  `developers_dev_id` INT(11) NOT NULL,
  `skills_skill_id` INT(11) NOT NULL,
  PRIMARY KEY (`developers_dev_id`, `skills_skill_id`),
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_skill_id` ASC),
  INDEX `fk_developers_has_skills_developers_idx` (`developers_dev_id` ASC),
  CONSTRAINT `fk_developers_has_skills_developers`
    FOREIGN KEY (`developers_dev_id`)
    REFERENCES `ilya_db`.`developers` (`dev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`skills_skill_id`)
    REFERENCES `ilya_db`.`skills` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilya_db`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `companies_company_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `companies_company_id`),
  INDEX `fk_projects_companies1_idx` (`companies_company_id` ASC),
  CONSTRAINT `fk_projects_companies1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `ilya_db`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilya_db`.`projects_has_developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`projects_has_developers` (
  `projects_project_id` INT NOT NULL,
  `developers_dev_id` INT(11) NOT NULL,
  PRIMARY KEY (`projects_project_id`, `developers_dev_id`),
  INDEX `fk_projects_has_developers_developers1_idx` (`developers_dev_id` ASC),
  INDEX `fk_projects_has_developers_projects1_idx` (`projects_project_id` ASC),
  CONSTRAINT `fk_projects_has_developers_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `ilya_db`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_developers_developers1`
    FOREIGN KEY (`developers_dev_id`)
    REFERENCES `ilya_db`.`developers` (`dev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilya_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilya_db`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `projects_project_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `projects_project_id`),
  INDEX `fk_customers_projects1_idx` (`projects_project_id` ASC),
  CONSTRAINT `fk_customers_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `ilya_db`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
